logging:
  level:
    root: warn
    cn:
      xhhtz:
        sbe: debug
    org:
      springframework:
        security: debug
        web: error
      apache:
        commons:
          dbcp2: debug
  file:
    path: C:/MySoftware/sbe/logs
    max-size: 1MB
spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 1000MB
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: root
  #    password: 123456
  #    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    open-in-view: false
  aop:
    auto: true
    proxy-target-class: true
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password:
#    timeout: 0
#    jedis:
#      pool:
#        max-active: 20

#mybatis:
#  config-location: classpath:mapper/mybatis-config.xml
#  mapper-locations: classpath:mapper/**/*Dao.xml
#  type-aliases-package: cn.xhhtz.sbe.entity

server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  tomcat.uri-encoding: UTF-8
  servlet:
    session:
      timeout: PT30M


extconfig:
  pathlocation: C:/MySoftware/sbe
  pathpattern: /f